var annotated_dup =
[
    [ "acrn_create_vcpu", "group__acrn__hypercall.html#structacrn__create__vcpu", "group__acrn__hypercall_structacrn__create__vcpu" ],
    [ "acrn_create_vm", "group__acrn__hypercall.html#structacrn__create__vm", "group__acrn__hypercall_structacrn__create__vm" ],
    [ "acrn_irqline", "group__acrn__hypercall.html#structacrn__irqline", "group__acrn__hypercall_structacrn__irqline" ],
    [ "acrn_msi_entry", "group__acrn__hypercall.html#structacrn__msi__entry", "group__acrn__hypercall_structacrn__msi__entry" ],
    [ "acrn_nmi_entry", "group__acrn__hypercall.html#structacrn__nmi__entry", "group__acrn__hypercall_structacrn__nmi__entry" ],
    [ "acrn_set_ioreq_buffer", "group__acrn__hypercall.html#structacrn__set__ioreq__buffer", "group__acrn__hypercall_structacrn__set__ioreq__buffer" ],
    [ "acrn_vm_pci_msix_remap", "group__acrn__hypercall.html#structacrn__vm__pci__msix__remap", "group__acrn__hypercall_structacrn__vm__pci__msix__remap" ],
    [ "hc_api_version", "group__acrn__hypercall.html#structhc__api__version", "group__acrn__hypercall_structhc__api__version" ],
    [ "hc_ptdev_irq", "group__acrn__hypercall.html#structhc__ptdev__irq", "group__acrn__hypercall_structhc__ptdev__irq" ],
    [ "hc_ptdev_irq.is", "group__acrn__hypercall.html#unionhc__ptdev__irq_8is", "group__acrn__hypercall_unionhc__ptdev__irq_8is" ],
    [ "hc_ptdev_irq.is.intx", "group__acrn__hypercall.html#structhc__ptdev__irq_8is_8intx", "group__acrn__hypercall_structhc__ptdev__irq_8is_8intx" ],
    [ "hc_ptdev_irq.is.msix", "group__acrn__hypercall.html#structhc__ptdev__irq_8is_8msix", "group__acrn__hypercall_structhc__ptdev__irq_8is_8msix" ],
    [ "mmio_request", "group__acrn__hypercall.html#structmmio__request", "group__acrn__hypercall_structmmio__request" ],
    [ "pci_request", "group__acrn__hypercall.html#structpci__request", "group__acrn__hypercall_structpci__request" ],
    [ "pio_request", "group__acrn__hypercall.html#structpio__request", "group__acrn__hypercall_structpio__request" ],
    [ "sbuf_setup_param", "group__acrn__hypercall.html#structsbuf__setup__param", "group__acrn__hypercall_structsbuf__setup__param" ],
    [ "vhm_request", "group__acrn__hypercall.html#structvhm__request", "group__acrn__hypercall_structvhm__request" ],
    [ "vhm_request.reqs", "group__acrn__hypercall.html#unionvhm__request_8reqs", "group__acrn__hypercall_unionvhm__request_8reqs" ],
    [ "vhm_request_buffer", "group__acrn__hypercall.html#structvhm__request__buffer", null ],
    [ "virtio_base", "group__acrn__virtio.html#structvirtio__base", "group__acrn__virtio_structvirtio__base" ],
    [ "virtio_desc", "group__acrn__virtio.html#structvirtio__desc", "group__acrn__virtio_structvirtio__desc" ],
    [ "virtio_ops", "structvirtio__ops.html", "structvirtio__ops" ],
    [ "virtio_used", "group__acrn__virtio.html#structvirtio__used", "group__acrn__virtio_structvirtio__used" ],
    [ "virtio_vq_info", "structvirtio__vq__info.html", "structvirtio__vq__info" ],
    [ "vm_gpa2hpa", "group__acrn__hypercall.html#structvm__gpa2hpa", "group__acrn__hypercall_structvm__gpa2hpa" ],
    [ "vm_set_memmap", "group__acrn__hypercall.html#structvm__set__memmap", "group__acrn__hypercall_structvm__set__memmap" ],
    [ "vring_avail", "group__acrn__virtio.html#structvring__avail", "group__acrn__virtio_structvring__avail" ],
    [ "vring_used", "group__acrn__virtio.html#structvring__used", "group__acrn__virtio_structvring__used" ]
];